### PR TITLE
Adding Functional prediction and Population prevalence

### PR DESCRIPTION
**Pull request by leexgh**
### try
`17:g.7577094G>A`
image

### PolyPhen -2 tooltip

image

### Mutation Assessor tooltip

image

### SIFT tooltip

image

### CODE REVIEW

**Comment by onursumer** [comment]
I think some of these components are copied from `cbioportal-frontend` repo, right? We should avoid code duplication. Since these components are only used in the mutation table we should probably move those into `react-mutation-mapper` repo. We can then import them both in `cbiportal-frontend` repo and here. We can also consider moving these into `cbioportal-frontend-commons` if we think the use-case for these components are more common.

@inodb @leexgh What do you think?

**Comment by leexgh** [comment]
@onursumer good idea, i'll mark the components copied from `cbioportal-frontend`

**Comment by inodb** [comment]
Thanks so much @leexgh ! Nice work on figuring out the score ranges.

Some minor points:
- Mutation Assessor score range seems a little weird. Wonder if that's for the variants they checked in that paper or a real min/max limit?
- The circle in the legend doesn't look round and the dot is quite big. Maybe a small circle looks better?
- Not sure if we should show the sources with the brackets: `[source]`.  The design doesn't look super clean to me. Maybe it needs some more padding between the source and the value?

**Comment by leexgh** [comment]
@inodb thanks for review
1. I guess it's for a real min and max, but not super sure. I checked the original paper but I only find the score thresholds, looks like it didn't mention the limits(or I missed it). 
https://academic.oup.com/nar/article/39/17/e118/2411278
2. will do
3. I'll try adding a little more padding or maybe remove the `[]` and see the results

**Comment by leexgh** [comment]
@inodb @onursumer could you take a look again? thanks

**Comment by inodb** [comment]
Thanks @leexgh ! Looks nice!

- Can the tooltip mouseover event span the whole element of source + value? E.g. for `PolyPhen-2
probably_damaging`: instead of having the tooltip disappear when you move the mouse between the words `PolyPhen-2` and `probably_damaging`, it continues to show. The tooltip only disappears when you move the mouse away from the element that spans both the source + the value.

**Comment by leexgh** [comment]
@inodb fixed, thanks for testing

**Pull request merged**
