### PR TITLE
search box enhancements

### PR DESCRIPTION
**Pull request by leexgh**
- search bar in center of page
- auto focus on search bar
- add search icon
- left align cursor

fix https://github.com/genome-nexus/genome-nexus/issues/334

image

### CODE REVIEW

**Comment by leexgh** [comment]
@inodb How do you like this one? I removed the button and added a search icon on the left.

**Comment by inodb** [comment]
Thanks @leexgh ! Looks great ✨ ! Would it be possible to make it a bit less wide and the cursor left aligned? The queries people type in will usually be pretty short

**Comment by leexgh** [comment]
@inodb sure, will do

**Comment by leexgh** [comment]
@inodb Updated, could you take a look?

**Comment by inodb** [comment]
Thanks @leexgh! Looks nice!

Minor thing: it feels a little strange that the cursor becomes centered when you start typing. I think it should stay left aligned

**Comment by leexgh** [comment]
@inodb fixed

**Pull request merged**
