### PR TITLE
Make sift section expandable

### PR DESCRIPTION
**Pull request by onursumer**
Related to genome-nexus/genome-nexus#534

### CODE REVIEW

**Review by inodb — APPROVED** [review]
LGTM

**Comment by inodb** [comment]
@onursumer actually - just noticed something. When you expand the horizontal bar between Functional Prediction and Biological function seems to disappear

Screen Shot 2021-09-01 at 10 46 03 AM

**Review by leexgh — APPROVED** [review]
👍

**Comment by onursumer** [comment]
> @onursumer actually - just noticed something. When you expand the horizontal bar between Functional Prediction and Biological function seems to disappear
> 
> Screen Shot 2021-09-01 at 10 46 03 AM

@inodb hmm, weird. I cannot reproduce this. Which browser are you using?

**Comment by inodb** [comment]
@onursumer ah interesting. Yeah I don't see it in Chrome. Only in Brave

**Comment by onursumer** [comment]
> @onursumer ah interesting. Yeah I don't see it in Chrome. Only in Brave

@inodb I can't reproduce it in Brave either. Maybe some specific combination of OS and the browser versions issue?

**Comment by inodb** [comment]
@onursumer hmm interesting - ok not a big deal then in any case. Feel free to merge

**Pull request merged**
