### PR TITLE
Add gnomad and dbsnp to variant page

### PR DESCRIPTION
**Pull request by leexgh**
try with `17:g.41258551C>A`

- [x] add gnomad data to variant page
- [x] center the content
- [x] add dbsnp

TODO:
we can try different styles or design later, since we don't have much data now

### CODE REVIEW

**Comment by inodb** [comment]
Thanks @leexgh ! It would be good to have a link to the variant in gnomad. Maybe one can click on `[gnomAD]`?

Some minor thing with the tooltip, it's not pointing to gnomad, but to population prevalence

Screen Shot 2019-11-04 at 2 12 12 PM

**Comment by leexgh** [comment]
@inodb for the gnomad tooltip I think Onur fixed it in mutation mapper.
@onursumer did this PR fix the issue above ( https://github.com/cBioPortal/react-mutation-mapper/pull/114 )?

**Comment by leexgh** [comment]
@inodb we have the link to the variant in gnomad - click the `gnomad` under the table. Do we still need another link on `[gnomad]`?

**Comment by leexgh** [comment]
@inodb @onursumer thanks for review, I close this PR cause new PR already includes the code

**Pull request closed without merging**
